### PR TITLE
Store binary crash reports in S3

### PR DESCRIPTION
**Pull request by aekeus**

### CODE REVIEW

**Comment by bbondy** [comment]
I think we need to put the minidump on s3.
We can clear out old ones per discussed on email but I think we should be keeping these in general for future code. Until we can download though, which is important too, the dumps aren't very useful.   If this is just temporary I'm ok with merging.

**Comment by aekeus** [comment]
We can add code to drop the minidump on S3 keyed against the id of the stored Mongo object if you would like.

**Comment by bbondy** [comment]
> if you would like.
:)
Sounds good, unless you have a better suggestion?
You can wait to do that until we have the downloading done though if you want.

**Comment by aekeus** [comment]
Ok, minidump files are now stored on S3 when a crash occurs. We will need to config three new environment variables before this branch will work in prod:

  S3_CRASH_BUCKET
  S3_CRASH_KEY
  S3_CRASH_SECRET

This PR was tested by spinning up a new Heroku app, configuring it to write to a new Mongo and S3. A crash was forced on the laptop browser. The correct record was written to Mongo and the minidump file was transferred to S3 successfully.

**Comment by aekeus** [comment]
Added option to easily disable S3 crash file storage. This will be useful if we need to shut off crash storage quickly.

**Pull request merged**
