### PR TITLE
Update to Bitwarden 1.27.0

### PR DESCRIPTION
**Pull request by da2x**
Resolves issue #48.

### CODE REVIEW

**Comment by Jacalz** [comment]
It isn’t really as easy as just updating it here in the repo but I will go through and test to see if the newer version works as I usually do with Bitwarden updates. If it works without any hiccups, then it’s fine on my end but then it needs to be pushed to the server...

**Comment by da2x** [comment]
@Jacalz what is the update process then? Surely there is a process for detecting upstream updates and updating these extensions? Current version in Brave no longer syncs with Bitwarden.

**Comment by Jacalz** [comment]
Yeah the way we do it is that me and @sampson usually sit down and go through and try if there are any issues with the extensions and if there are non we update them. Bitwarden has not been getting updates due to time differences and being busy with Luther stuff... This will get solved though with Brave 1.0 that will be coming out later this year: https://github.com/brave/brave-browser

**Comment by Jacalz** [comment]
Will as I said see if I can test the extension later this week and the. We can see if we can get it merged 🙂

**Comment by Jacalz** [comment]
It looks like the latest version works perfect without any issues, this is fine for me 👍

**Comment by Jacalz** [comment]
I believe that this can be closed now since https://github.com/brave/vault-updater/commit/20035247338d0335e9ccfcc5675dd7ab72764daf is on the master branch now...

**Comment by Jacalz** [comment]
@kspearin There isn’t really any process as to requesting reviews. I usually see the release and test it as soon as possible but then someone with acces to the sever needs to push it after I ask to get it updated. I will see if the new version works and if that’s the case, I will ask someone to update it hers and on the server🙂

**Pull request closed without merging**
