### PR TITLE
Update to address vulnerabilities

### PR DESCRIPTION
**Pull request by bsclifton**
## Description
This resolves all `HIGH` vulnerabilities

`npm audit` now reports:
`found 20 vulnerabilities (1 low, 19 moderate) in 3835 scanned packages`

Some of what was done:
- `npm audit fix`
- - manually upgrading `hapi` to 13.5.3 (following guide at https://github.com/hapijs/hapi/issues?q=is%3Aissue+label%3A%22release+notes%22)
- manually upgrading `hapi` to 14.2.0 (following guide at https://github.com/hapijs/hapi/issues?q=is%3Aissue+label%3A%22release+notes%22)

## Help needed
Running `npm run test` before AND after this change reports the same number of pass/fails:
```
67 passing (6s)
  3 failing
```

I am not exactly sure of a good way to properly test these changes. Could use some help 😄 cc: @aekeus

### CODE REVIEW

**Comment by aekeus** [comment]
Upgrading HAPI will fundamentally change the required implementation of the endpoint definitions. The current tests do not exercise the required functionality. stats has recently gone through this process, but it required a non-trivial amount of manual testing. The same will be required here.

**Comment by diracdeltas** [comment]
@aekeus @bsclifton what are suggested next steps here to get this merged? it would be good to get these security fixes out.

**Comment by aekeus** [comment]
I have a sizeable re-factor of this system largely complete. It addresses all the security items that were flagged as well as increasing the test coverage.

**Comment by diracdeltas** [comment]
thanks @aekeus !

**Comment by bsclifton** [comment]
@aekeus awesome! I'll go ahead and close this one out 😄

**Pull request closed without merging**
